// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFcAAztWlaXHvY4bcHFZPa2idZdzBrNaE',
    appId: '1:996085390532:web:60cf47af0410bd1a9e7d91',
    messagingSenderId: '996085390532',
    projectId: 'our-bung-play',
    authDomain: 'our-bung-play.firebaseapp.com',
    storageBucket: 'our-bung-play.firebasestorage.app',
    measurementId: 'G-GF7HGEGXJV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7cLPCIwtovSrPxpA9sqGYUAE1F5mRBm4',
    appId: '1:996085390532:android:0bce0ca1cdfdad2f9e7d91',
    messagingSenderId: '996085390532',
    projectId: 'our-bung-play',
    storageBucket: 'our-bung-play.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCopJzoMmgWbtEvAjex9E7Yi8YA1cXuw6I',
    appId: '1:996085390532:ios:c4bc3939ae7035cc9e7d91',
    messagingSenderId: '996085390532',
    projectId: 'our-bung-play',
    storageBucket: 'our-bung-play.firebasestorage.app',
    iosClientId: '996085390532-qv01f8c7rig7n3ti4bake5b0ipksiml0.apps.googleusercontent.com',
    iosBundleId: 'com.example.ourBungPlay',
  );

}